stages:
  - build-push

docker-build:
  image: docker:latest
  stage: build-push
  services:
    - docker:dind
  tags:
    - docker
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}
    - docker push ${CI_REGISTRY_IMAGE}:latest
